language: python
install:
    pip install tox
env:
    matrix:
        - TOXENV=py27-django18
        - TOXENV=py27-django19
        - TOXENV=py27-django110
        - TOXENV=py27-django111
        - TOXENV=flake8
script: make test
